// import NavBar from './components/navBar'
import Footer from "./components/footerComponents/footer";
import NavBar from "./components/navBar/navBar";
import "./globals.css";
import { Benne } from "next/font/google";

const benne = Benne({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={benne.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
